### ISSUE TITLE
API Keys saved in clear in the database

### ISSUE THREAD

**Issue by proxeus-dev** [ProxeusApp/proxeus-core#1]
API Keys are currently saved in clear when configuring the Proxeus server. Instead, like modern Cloud Native applications, these keys should not be saved in the database at all. They should not need to be edited by system administrators on the fly. 

It is in any case right now necessary to restart the application to apply changes to the keys. This should be made clear in the documentation.

### Steps to reproduce
Go to configuration settings and edit the API keys to remote services.

### Expected behaviour
Configuration keys are stored only in configuration files (.env or .yml), loaded on startup. They are not stored in the database.

### Actual behaviour
It is not encrypted in the database, and shown in plain text to administrators, both are security risks.

**Comment by javany** [comment]
Using a symmetric algorithm is helpful in this case.using AES package, I added two functions for encrypting/decrypting the values for writing/reading to/from the settings db.
