### ISSUE TITLE
Add JSON Sender Node as workflow element

### ISSUE THREAD

**Issue by stefanvogel65** [ProxeusApp/proxeus-core#176]
### Enhancement: Add workflow node to send JSON data as http POST

The data captured in a workflow need to be POSTed to a REST endpoint for post processing of the data. This is implemented in the Handelsregister version of Proxeus implementation as "IBM sender" . 

The node should be generic and configurable in terms of API endpoint URL and authentication parameters. The following is a set of parameters that are used in the current "IBM sender" implementation and would be sufficient:

```JSON
{
    "config": {
        "url": "host:port/endpoint"
    },
    "header": {
        "Content-Type": "application/json",
        "clientid": "enter client id",
        "tenantid": "enter tenannt id",
        "secret": "enter the secret",
        "oauthserverurl": "enter the oauthserver url"
    }
}
```

### Expected behavior

When the node executes in a workflow, a HTTP POST is called that posts the current set of data captured in all forms to the endpoint as a JSON. This POST corresponds to a curl command like this:

```
curl --location --request POST '<enpoint url>' \
--header 'clientid: <client id>' \
--header 'tenantid: <tenant id>' \
--header 'secret: <secret>' \
--header 'oauthserverurl: <oauth url>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "data": "goes here"
}'
```

**Comment by loleg** [comment]
@stefanvogel65 we have (finally!..) merged the PR that was attached to this issue. Would be interested in giving it a quick test?
