### ISSUE TITLE
Demo no longer signing workflows

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#190]
Despite being logged in with a linked account, I get the message 

> _"Make sure that you are logged into the correct account in MetaMask. The Document-Registration must be made from the ethereum-account that you have connected in your account settings. Switch Metamask account and make sure that you have set your ethereum address in your account account settings on the top right."_

Possibly linked to this: a 400 error on `https://demo.proxeus.com/api/user/document?i=1` in the console

Likely to be linked to #23

**Comment by tommyyama2020** [comment]
Hello 

I have a similar issue today. I am wondering who is maintaining this now..
![Screen Shot 2020-11-21 at 19 59 20](https://user-images.githubusercontent.com/38548157/99875565-13615700-2c34-11eb-8ad2-63eb9589d73a.png)

![Screen Shot 2020-11-21 at 19 56 49](https://user-images.githubusercontent.com/38548157/99875538-e90f9980-2c33-11eb-9466-96994653221e.png)

**Comment by twenster** [comment]
Hi @tommyyama2020,

Thanks you for the screenshots! We will look at it as much as we can.

**Comment by tommyyama2020** [comment]
thanks! glad to see a human being's comment here, haha🙂

**Comment by loleg** [comment]
@tommyyama2020 we are testing a new release as part of https://github.com/ProxeusApp/proxeus-core/projects/1 and will be happy to have your feedback. Please stay tuned!

**Comment by loleg** [comment]
Closing, as this has been fixed in the last patches.
