### ISSUE TITLE
Message "missing page" when a user tries to signup

### ISSUE THREAD

**Issue by VivienFuhrer** [ProxeusApp/proxeus-core#210]
### Subject of the issue
When a new user tries to signup for a one-click Proxeus instance - there is a message "missing page" displayed by my browser.

### Your environment
PC - Brave

### Steps to reproduce
proxeus.startupcfo.ch  (one-click install) signup

### Expected behaviour
No warning message from my browser

### Actual behaviour
Warning message displayed "missing page"
![image](https://user-images.githubusercontent.com/25813493/111955555-f22d4c00-8ae9-11eb-9971-7b6dc6331af7.png)

**Comment by loleg** [comment]
This is a feature of your browser, which attempts to fetch a last known copy of a web page when it is missing. The actual problem is that your server is unresponsive. Please test your issue in a basic profile (minimal plugins) of Chrome or Firefox.
