### ISSUE TITLE
Better user alert when web3 is not accessible

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#226]
Currently when a user who does not have web3 support in the browser (i.e. [MetaMask](https://metamask.zendesk.com/hc/en-us/articles/360053147012) or similar wallet extension) installed sees a very generic error message. In the console however it is clear that the issue is that `web3` is missing. We should detect this and provide a more appropriate notification.

![JmludJMR](https://user-images.githubusercontent.com/31819/125611902-9a8e41d7-2ec8-43c8-9563-2026e6eb577e.jpg)

**Comment by tafonina** [comment]
Should be assigned to frontend dev

**Comment by loleg** [comment]
Note this applies only to users who have logged in without Metamask.

**Comment by tafonina** [comment]
middle priority

**Comment by loleg** [comment]
Also an issue when you have the wrong network selected, says @tafonina

**Comment by loleg** [comment]
As discussed, Tatiana will try to reproduce this in a different workflow (e.g. when user goes offline).

**Comment by loleg** [comment]
See also #410 in case it makes a difference to how this is done.

**Comment by tafonina** [comment]
Tried to reproduce:
when user doesn't have metamask - he can see user friendly message


![Image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/d1aa4056-f8c2-44ad-a11f-7624513d8b59)

if user has metamask but network is not correct (not the same as currently in proxeus settings) - the error is also user friendly

![Image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/4f606d5f-263c-40cf-8d7d-5769a47f0c5b)

task can be closed

**Comment by tafonina** [comment]
moreover - in the ticket #315 @slavas490 will add verification and prompt user to change the network

**Comment by loleg** [comment]
Thanks @tafonina great.
