### ISSUE TITLE
Document workflow does not run anymore

### ISSUE THREAD

**Issue by stefanvogel65** [ProxeusApp/proxeus-core#248]
### Subject of the issue

Since we deployed the new Proxeus core image, the document workflow does not run any more. It just shows a blank page only with the back button, the language picker, and the user icon as shown in the screenshot:

![image](https://user-images.githubusercontent.com/35991100/150388611-5695b830-a184-44c6-b9fe-4ece539be89b.png)

Also, the template test view does not offer any input fields any more:

![image](https://user-images.githubusercontent.com/35991100/150390134-9496a5c5-0a51-4e41-b7c3-38bf82618317.png)

### Your environment

Deployment on OpenShift on IBM Cloud (ROKS).

### Steps to reproduce

Same settings and setup that worked with the image as of Oct 2021 (only added the newly required variable for PROXEUS_ENCRYPTION_SECRET_KEY).

### Expected behaviour

When you run a workflow, first form of workflow should be displayed.

In the test template view, a list of form fields should be offered to input test values like before:

![image](https://user-images.githubusercontent.com/35991100/150390431-90ac7005-804b-49c0-ae4d-a813c406db3f.png)

### Actual behaviour

See screenshots above.

**Comment by loleg** [comment]
Apologies for the delay here, we are on-boarding a new developer this week, and I have managed to reproduce the issue in a local environment. Will keep you posted.

**Comment by stefanvogel65** [comment]
Thanks for the update. Looking forward for your finding and the fix. When you build a new image of the fix, could you start to use version labels on the corresponding docker images? Thanks.
