### ISSUE TITLE
Encryption variable missing in Quickstart guide

### ISSUE THREAD

**Issue by Tatamanilo** [ProxeusApp/proxeus-core#254]
### Subject of the issue
in the pull request https://github.com/ProxeusApp/proxeus-core/pull/229 the Encryption mechanism is added for storing and retrieving API keys, but in documentation for quick start - this variable is missed in the list that user should specify. It can cause problems when developer building up the platform, specify the length of the secret key (32 symbols)

### Steps to reproduce
Follow quickstart guide, run platform via docker-compose up

### Expected behaviour
properly running container xes-platform 

### Actual behaviour
The PROXEUS_ENCRYPTION_SECRET_KEY variable is not set. Defaulting to a blank string.
Container xes-platform  is not up
![image](https://user-images.githubusercontent.com/40423090/154692030-78c9d359-8a6f-4e45-a410-807d69fee724.png)
xes-platform               | 2022/02/18 14:32:52 Unable to start Proxeus.

### Solution
 should be set as default value in docker-compose + updated doc for Quick start

- /docs/quickstart.md; 
- http://doc.proxeus.com/#/README

add this valiable in the list of export:

```
Run the following command in the directory containing your docker-compose.yml file (Linux and OSX):
export PROXEUS_ENCRYPTION_SECRET_KEY?=PleAsE_chAnGe_me_32_Characters++
```

**Comment by loleg** [comment]
We need to clarify where developers update the docs.

**Comment by tafonina** [comment]
@loleg  clarify pls the source of http://doc.proxeus.com/#/README

**Comment by loleg** [comment]
This was fixed a while ago, thanks everyone.
