### ISSUE TITLE
Artifacts with methods to old smart contracts

### ISSUE THREAD

**Issue by tafonina** [ProxeusApp/proxeus-core#255]
### Subject of the issue
In the code there are calls to old or nonexistent methods of smart contracts:
**example** file `ui/wallet/src/ProxeusEthereum/services/ProxeusFS.js`

> line 8
```
async XESAmountPerFile ({ providers }) {
    return this.contract.methods.getXESPrice().call()
  }
```

> line 25
```
fileHasSP (hash, spAddress) {
    return this.contract.methods.fileHasSP(hash, spAddress).call()
  }
```

- `getXESPrice` doesnt exist in ProxeusFS contract
- `fileHasSP` exists only in old contract (repo storage-app)

### Solution 
check is ProxeusFS service is used, get rid of artifacts check other cases of unused contract methods:
The actual list of ProxeusFS smart contract methods:

- registerFile
- verifyFile
- signFile
- getFileSigners

**Comment by slavas490** [comment]
@tafonina  @loleg  https://github.com/sprotest/proxeus-core/tree/feature/remove-old-smartcontract-methods
