### ISSUE TITLE
Metamask error, Please grant access to MetaMask

### ISSUE THREAD

**Issue by tafonina** [ProxeusApp/proxeus-core#260]
### Subject of the issue
Metamask error

### Your environment

- seraphim env;
- local env which is built from dockerhub latest image, or run on current code on master

### Steps to reproduce
Click login or signup:

https://seraphim.proxeus.org/login
-> Log in with Metamask

https://seraphim.proxeus.org/register
->Sign up with Metamask

### Expected behaviour
User should be proposed to sign message with Metamask and then authorized to system

### Actual behaviour
We can see UI error: Please grant access to MetaMask.
![image](https://user-images.githubusercontent.com/99973342/164270939-e9447c5e-4b42-4070-8d2e-b69c0685e0c1.png)

Error in console: 
`TypeError: this.app.wallet.wallet.setupDefaultAccount is not a function
    at o.metamaskLogin (frontend.0e9ce44b.js:1:3669)`
![image](https://user-images.githubusercontent.com/99973342/164271087-ccc62a76-08b0-4884-a0ce-06fdb445ad32.png)

### Possible problem and solution:
we have such wallets:

- ui/wallet/src/ProxeusEthereum/ProxeusWallet.js
- ui/wallet/src/ProxeusEthereum/MetamaskWallet.js

and exactly MetamaskWallet should be injected in this case, but in fact - the ProxeusWallet is used (it doesn't have method setupDefaultAccount)

the problem is in the WalletInterface constructor (line 18)
`this.useProxeusWallet = forceProxeusWallet || typeof window.ethereum !== 'undefined'`

**Comment by loleg** [comment]
Linked to #226

**Comment by tafonina** [comment]
it was incorrect logic (this.useProxeusWallet = forceProxeusWallet || typeof window.ethereum !== 'undefined')
fixed with change 
typeof window.ethereum !== 'undefined' 
to 
typeof window.ethereum === 'undefined'

useProxeusWallet should be true only if user doesn't have metamask (in this case window.ethereum is undefined) or forceProxeusWallet is true

**Comment by loleg** [comment]
Fixed and released!
