### ISSUE TITLE
Broken create document flow

### ISSUE THREAD

**Issue by tafonina** [ProxeusApp/proxeus-core#266]
### Subject of the issue
when admin created workflow, it is impossible to run it

BE seems to return good results
![image](https://user-images.githubusercontent.com/99973342/177608663-920b6e67-e59a-4843-924f-38ad33a76850.png)

but FE
there is console errors
![image](https://user-images.githubusercontent.com/99973342/177608559-3affc2a2-cf7a-4460-8925-ec2ae792f772.png)

### Your environment
local, master branch of proxeus-core
### Steps to reproduce
As admin: create the workflow, click "run". 
the same will be for user:
User view->Documents->Create document

### Expected behaviour
User should be able to pass the worflow and create document
![image](https://user-images.githubusercontent.com/99973342/177609139-1526d99a-7e73-4e48-9446-2917d0113a6e.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/99973342/177609208-a3e3ea5b-ee12-4a2f-9fcc-d12055f56372.png)

**Comment by loleg** [comment]
@tafonina please close if no longer applies.
