### ISSUE TITLE
Update Watchtower support

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#275]
An old version of Watchtower is used in the Docker-Compose configuration, which does not work properly any more. See https://containrrr.dev/watchtower/

**Comment by tafonina** [comment]
@loleg can you add pls **sprotest** account to this project
Devops will check this ticket

**Comment by tafonina** [comment]
@loleg assign pls sprotest to this ticket

**Comment by sprotest** [comment]
For review 

https://github.com/ProxeusApp/proxeus-core/pull/294
