### ISSUE TITLE
Move to main branch

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#284]
Instead of `master` use the `main` branch going forward. Additionally, we will ask all contributors to use Git Flow with feature branches to make merges easier to follow. Any other suggestions of how to improve the use of Git and GitHub, please add to this issue.

**Comment by tafonina** [comment]
before merging to main, pls create PR to preprod branch first. Preprod branch it is mapped to stage environment https://core.proxeusapp.stage.scenario-projects.com/ - so before merging to main there is change to check the stability of the platform

**Comment by tafonina** [comment]
We will discuss it on the grooming session

**Comment by loleg** [comment]
The default branch has been renamed! **master** is now named **main**

If you have a local clone, you can update it by running the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by tafonina** [comment]
@loleg thanks
