### ISSUE TITLE
Metamask console error

### ISSUE THREAD

**Issue by tafonina** [ProxeusApp/proxeus-core#285]
MetaMask no longer injects web3
but in baseApp.js it is still used 
so we have console error TypeError: Cannot read properties of undefined (reading 'getAccounts')
![image](https://user-images.githubusercontent.com/99973342/208404831-99b9a6e0-be06-4f14-90a7-68b95fd93f69.png)

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by loleg** [comment]
@tafonina please close if this has been fixed.

**Comment by tafonina** [comment]
The issue is fixed but only on preprod branch. Lets close it as soon as the fixes will be in master branch

**Comment by tafonina** [comment]
@loleg 
The issue is fixed but only on preprod branch. Lets close it as soon as the fixes will be in master branch
