### ISSUE TITLE
Preview and download broken in prod

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#292]
It is not possible to download a copy of a document that has been generated with a Proxeus workflow. This bug **only affects production servers**, it can not be reproduced yet on a local machine.

### Your environment

<img width="1451" alt="Screenshot 2023-02-06 at 14 24 44" src="https://user-images.githubusercontent.com/31819/218442818-da501dfb-920d-489e-818e-80b78718ed50.png">

All browsers. Screenshot from Chrome by @Halil-Kuray 

### Steps to reproduce

- Go through the normal steps to create a document from a form and template
- After the document hash is saved on the blockchain, you are directed to the User view where normally you can download a document - but you can't

### Expected behaviour

You should be able to see and download your document.

### Actual behaviour

You just see a spinning icon, no thumbnail is shown - and no error, either.

**Comment by loleg** [comment]
Last week we debugged this together, and saw that there were no errors on the server log being registered. However, there was a 404 in the JavaScript, and when directly accessed (@tafonina can tell us what part of the URL to modify), the endpoint does allow the PDF to be downloaded.

Since the problem does not occur on local development, I strongly suspect this to be an issue with the web proxy (i.e. nginx), which sometimes had problems with special characters in endpoints - and we do have square brackets (...`doc[0]` or so) in the URL.

**Comment by tafonina** [comment]
on dev/stage file ....worker.js has 404 status code.
![image](https://user-images.githubusercontent.com/99973342/219106481-f0f6b91f-5530-4d28-9852-9d0da7e65488.png)
Physically the file exists on dist/ folder.
Locally this file is fetching correctly
![image](https://user-images.githubusercontent.com/99973342/219107074-213836d6-d0e1-467d-a735-1ffcc4b834ee.png)
It can be closely related to the bug with document preview

**Comment by loleg** [comment]
I still think that this has to do with the call to 
`/api/user/document/signingRequests/ac1c2e99-8c2f-463d-b80b-29a0bce28547/docs[0]`
and that the error is thrown from either the Web server, or the function `UserDocumentSignatureRequestGetByDocumentIDHandler` line 1582. We should add a debugging statement there.

**Comment by tafonina** [comment]
the problem was in this non-accessible .worker.js file. The new PR to preprod branch is already created and merged.
