### ISSUE TITLE
Email node does not work.

### ISSUE THREAD

**Issue by Halil-Kuray** [ProxeusApp/proxeus-core#293]
### Currently, the workflow works as seen in the photos below without an email Node.

- <img width="1470" alt="1" src="https://user-images.githubusercontent.com/71791007/218467859-f65899a3-a4f1-481e-ba70-d1daf5b48010.png">
- <img width="1470" alt="2" src="https://user-images.githubusercontent.com/71791007/218467926-87286926-90a1-4306-9a18-8fa928cb1d2f.png">
- <img width="1470" alt="3" src="https://user-images.githubusercontent.com/71791007/218467966-c2c5d62f-f768-4cf4-8d67-4d8ca27e49a4.png">
- <img width="1468" alt="4" src="https://user-images.githubusercontent.com/71791007/218468007-05aa33f4-9793-4836-a931-3daf23482947.png">

### Here's what happens when I add an email Node:

- <img width="1470" alt="5" src="https://user-images.githubusercontent.com/71791007/218468396-0bb60fea-02fe-47eb-997f-1b65a6787c9d.png">
- ![6](https://user-images.githubusercontent.com/71791007/218468421-7818b63b-c202-4217-8980-0346d26a1001.jpeg)

### Your environment
Stage server

### Steps to reproduce
You get this issue when you run a workflow with a mail node.

### Expected behaviour
When we look at the code in the github repo, the expected thing is to present a form to the user and wait for some information to be entered to send an email.

### Actual behaviour
I get an error when I try to run workflow.

**Comment by loleg** [comment]
As we discussed, this is not an issue that affects all nodes - please move to https://github.com/ProxeusApp/node-mail-sender/issues

**Comment by Halil-Kuray** [comment]
Modev to [here](https://github.com/ProxeusApp/node-mail-sender/issues/2#issue-1582534676)

**Comment by Halil-Kuray** [comment]
Moved to https://github.com/ProxeusApp/node-mail-sender/issues/2#issue-1582534676
