### ISSUE TITLE
Character limit in file naming

### ISSUE THREAD

**Issue by Ibrahim-Halil-Kuray** [ProxeusApp/proxeus-core#305]
### Subject of the issue
File naming is limited to 80 characters. When I exceed this limit, I get the error seen in the screenshot I added.
However, as seen in the screenshot, there is also a change in the layout.

![Screenshot 2023-05-03 at 08 22 58](https://user-images.githubusercontent.com/71791007/235846756-e07e385a-3950-45be-a5d4-89f874895aac.jpeg)

**Comment by slavas490** [comment]
Can't reproduce (as well as @tafonina). Let's move this issue to backlog

**Comment by loleg** [comment]
![Image](https://github.com/ProxeusApp/proxeus-core/assets/31819/2747045f-c84e-467c-aed9-b75580841281)

Click Documents in User View, open any document, start typing a long text in the Name. At some point the UI breaks and you see errors.
