### ISSUE TITLE
Not being able to add property 

### ISSUE THREAD

**Issue by Ibrahim-Halil-Kuray** [ProxeusApp/proxeus-core#306]
### Subject of the issue
When I delete a property, I can not bring it back. Instead, I have to add the component I want to use again to the form and modify it.

<img width="1468" alt="Screenshot 2023-05-03 at 09 33 07" src="https://user-images.githubusercontent.com/71791007/235856950-1b396e28-abb8-4daa-b51b-b79aa95ea303.png">

<img width="1470" alt="Screenshot 2023-05-03 at 09 33 16" src="https://user-images.githubusercontent.com/71791007/235856961-7cd2f79b-a82a-4f99-a9c7-d5423a07d9fc.png">

**Comment by loleg** [comment]
My suggestion is to not allow the user to (accidentally) delete properties. I do not see a use case for having this [ - ] button at all.

**Comment by loleg** [comment]
Or at least, add a confirmation "Are you sure you would like to delete this property? This action is not reversable."

**Comment by loleg** [comment]
The delete button has been removed.
