### ISSUE TITLE
Move IFrame'd admin-doc to inline content

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#311]
Change the link to the Handbook to this one:

https://doc.proxeus.org/#/handbook

We also need to look at the Terms of Use and Onboarding links...

![Image](https://github.com/ProxeusApp/proxeus-core/assets/31819/5b094044-4124-48f8-82db-e2cae5ca9940)

---

(OLD REQUIREMENT)

On a modern browser, I see a security error in the JS dev console when using the admin area: 

```
Blocked script execution in 'https://docs.google.com/document/d/1ZFWqwSUyCZ9f6Ts2jfFWU1lwegoctWWOjpXtAqP8NUI/preview' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

This is a Google Document being embedded in an IFRAME. Not a good practice in any case. It's only a short text, that I would rather see moved directly into `Admin.vue` or loaded from a local template.

Sometimes the error looks like this in the console:
![image](https://github.com/ProxeusApp/proxeus-core/assets/31819/c7d3d7a4-1cbe-466c-83d7-e5db0548e2db)

**Comment by loleg** [comment]
In order to complete this task, I have to refresh the i18n database.

**Comment by loleg** [comment]
Can we update https://github.com/ProxeusApp/proxeus-core/tree/main/demo/restore_db
using the same process as we use to restore the DEMO server?

**Comment by slavas490** [comment]
use this code for db update:

[dbexp.go.zip](https://github.com/ProxeusApp/proxeus-core/files/14450688/dbexp.go.zip)

**Comment by loleg** [comment]
Thanks, I'll apply the changes to a clean instance and create a PR.

**Comment by slavas490** [comment]
done
