### ISSUE TITLE
Error installing Go packages on Demo server

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#326]
Depending on the versions of Go in the environment, there are issues deploying the project with specific versions of packages. It seems like we need to hard-fix the versions of specific modules. Creating a Docker configuration for various environments could also help.

Docker instructions: http://doc.proxeus.com/#/docker

**Comment by Kamel-83** [comment]
potentially check if this is related to https://github.com/ProxeusApp/proxeus-core/issues/316

**Comment by Kamel-83** [comment]
related to issue #380
