### ISSUE TITLE
Radio input does not select a value

### ISSUE THREAD

**Issue by Ibrahim-Halil-Kuray** [ProxeusApp/proxeus-core#332]
### Subject of the issue
Radio button element

### Your environment
MacOS / Chrome browser/ Stage server

### Steps to reproduce
- I created a form  and put a radio button component there with a few options
- I created a proper template and a workflow
- In template section I was able to see the value I selected in my template
- When I run the workflow, select an option and try to continue it says: required (for radio button)
- When the radio button is not required, I don't see the value I selected in my document.

### Expected behaviour

The value I selected should reflected to my document

### Actual behaviour

I don't see the value in my document

**Comment by Ibrahim-Halil-Kuray** [comment]
Same thing happens with 'checkbox' as well.

**Comment by tafonina** [comment]
The bug is also found on the Forms->Test tab (found by Viacheslav Okhmak s-pro)
![image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/6d94003d-1032-4b88-bb54-c2ee3c392158)
