### ISSUE TITLE
Files containing error warnings

### ISSUE THREAD

**Issue by Ibrahim-Halil-Kuray** [ProxeusApp/proxeus-core#360]
## Subject of the issue

Some files have warning signs. I did not have the opportunity to test how these warnings affect the functionality of the application.
I also added the autogenerated files and specified all the files in detail. I did it this way because it might give you ideas about some other problems and in case there were some files I missed. I hope it will be instructive for the person assigned to the task.

#### Related style

- ui>core>dist>static>assets>css>user.9a7cb90c.css
- ui>core>dist>static>assets>css>initial.20876483.css
- ui>core>dist>static>assets>css>frontend.69c7fe25.css
- ui>core>src>views>Workflow.vue
- ui>core>src>assets>styles>legacy> most of the files (.css and .less)
- ui>core>src>libs>legacy>flowchart>tooltipster.bundle.min.css
- ui>core>src>libs>legacy>formbuilder>splitpane>split-pane.css
- ui>>core>src>components>SignatureRequestList.vue.   (pading-bottom: 2em;  (typos padding-bottom:))
- ui>>core>src>components>wallet>wallet.vue
- ui>>core>src>components>SignatureRequestList.vue
- ui>core>src>assets>styles folder (so many warnings)

#### Related import export and modules

- main>main_test.go
- storage>database>db>mongo_test.go
- storage>database>db>storm_test.go
- storage>portable>import-export.go
- go.mod

**Comment by loleg** [comment]
Thanks for the tip. We will check these as part of #362
