### ISSUE TITLE
Interrupted Draft has empty fields

### ISSUE THREAD

**Issue by tafonina** [ProxeusApp/proxeus-core#363]
### Subject of the issue
When user passes workflow and interrupts it - then opens it again - the fields are empty
![image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/4a81b4d1-7dc5-44f3-8972-9162cc3035e1)

though the values are returned to FE
![image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/ceb273a6-816d-4132-a96c-232a202b926e)

### Your environment
stage

### Steps to reproduce
start workflow, interupt,open it from the list of drafts

### Expected behaviour
the form should be filled out with saved values from the draft

**Comment by loleg** [comment]
@slavas490 please see if this is still a problem in DEV, and close otherwise.
