### ISSUE TITLE
Nodes modified values are not visible on next step

### ISSUE THREAD

**Issue by tafonina** [ProxeusApp/proxeus-core#364]
### Subject of the issue
If proxeus node modifis some values, they are not visible on next step (frontend issue), but after saving document to blockchain the changes are visible

### Your environment
stage

### Steps to reproduce
- create the form with field CHFXES
- cretae template with placeholder {{input.CHFXES}}
- create and save workflow like this
![image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/3e9fc9c9-0ce8-4e71-8c00-d044627c782f)
- run workflow
- input any value to price field (ex.5)
- before saving doc to blockchain the value remains 5, but it should be replaced with the value from price retriever node, but after user saves it to blockchain - evth is correct - in the doc he can see correct value - from price retriever
![image](https://github.com/ProxeusApp/proxeus-core/assets/99973342/1aa132e5-6fe1-4349-a5bf-068766b8e9bf)

### Expected behaviour
user should see value from price retriever on last step of workflow - before saving doc to blockchain

**Comment by loleg** [comment]
We decided that we need to add extra data, but not modify the input data. Therefore, this issue may not be as relevant as we initially thought. Please test:

- {{input.XXXX}} fields from the form are *not* changed
- {{output.XXXX}} fields are being used by the node
- {{output.XXXX}} fields are correctly filled in the preview of the document

**Comment by slavas490** [comment]
I've double checked this issue and the answer is - yes, it does not change the input data. As we already discussed node should response with some extra field, but do not modify already preset ones.
<img width="402" alt="on-next handler ts — proxeus-typescript-boilerplate 2024-01-31 22-41-09" src="https://github.com/ProxeusApp/proxeus-core/assets/12787657/aa49859b-477d-4575-a956-7dae7bad3255">
<img width="588" alt="Proxeus - test 2024-01-31 22-38-55" src="https://github.com/ProxeusApp/proxeus-core/assets/12787657/c146137a-b1c7-45cb-8f3a-ee62317be853">

**Comment by slavas490** [comment]
the form data I was using for this test
<img width="955" alt="111" src="https://github.com/ProxeusApp/proxeus-core/assets/12787657/a815e47e-2ac5-4340-914e-f3215a55881c">
