### ISSUE TITLE
Are you guy still working on this?

### ISSUE THREAD

**Issue by JOY** [ProxeusApp/proxeus-core#419]
The development speed is too slow. Are you still working on this cool project?

**Comment by loleg** [comment]
Yes! We have guys and gals working hard on maintaining the core Proxeus project. Watch out for a fresh release this week :rocket: We would be happy if you could test it and give us some feedback. We love to play and make games, and would be happy to talk to you about any applications you have in mind that could be powered up by this project.

I'm closing this issue, feel free to re-open if you have some more work for us :grimacing:
