### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#424]
As a user, I would like to bookmark links to a specific screen in the Proxeus application. However, if I am not logged in, I am presented with a login prompt. After login, the application always just goes to the default screen (Workflows list). Instead, I should be redirected to the URL that I bookmarked.

**Comment by slavas490** [comment]
already done and can be tested over here https://core.proxeusapp.dev.scenario-projects.com/

**Comment by slavas490** [comment]
done
