### ISSUE TITLE
Content for demo server

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#462]
Create a separate copy of the database dump (not the same as the "default" demo database that goes into new Proxeus installations), and restore that local version every night.

We can use the system of the [public demo/ folder](https://github.com/ProxeusApp/proxeus-core/tree/preprod/demo/restore_db), but we should not override the proxeus core "defaults" with the "DEMO SERVER" content.

## Introductory text (*)

Title: **Proxeus Demo**
Text:

> Proxeus is all about document-centered processes secured on the Blockchain: an app that lets you drag & drop a workflow in the wink of an eye, comprised of forms, document templates and conditions. Create tamper-proof and easily verifiable documents by registering them. This is a demo server, the content will be reset every 24 hours. If you need help write us an email to support@proxeus.org

- [x] Use the S-PRO logo as "default logo" of the server (top left corner)
- [x] Add some introductory text as Welcome (as above)
- [x] Update the Title (as above)

**Comment by loleg** [comment]
There has been some misunderstanding. The demo server needs to be a standard installation. No code changes. Any of the above requirements that cannot be done using the Internationalisation content or basic server settings must be dropped.

**Comment by slavas490** [comment]
done. please check the link https://proxeus-demo.s-pro-services.com/

**Comment by Kamel-83** [comment]
@slavas490 please add an attachment of the script to this ticket.

**Comment by slavas490** [comment]
Made these files:
1) _cronjob.sh_
2) _db_update.go_

Cron job (should be running under sudo user):
_0 0 * * *       /home/ec2-user/proxeus/cronjob.sh 1> /dev/null 2> /home/ec2-user/proxeus/cronjob.err_

[Archive.zip](https://github.com/ProxeusApp/proxeus-core/files/14450612/Archive.zip)

**Comment by loleg** [comment]
Thanks for updating this and #311 - done!
