### ISSUE TITLE
Divergent history in Git

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/proxeus-core#512]
When a developer submits a Pull Request on GitHub, many commits are visible in the log that are not part of the actual PR. These are changes that are already part of the `main` or `preprod` (i.e. staging) branch. This affects our ability to review PRs, because also many extra changes are in the diff.

Investigate if this is a known issue, see if we can get support from GitHub. 

See #509 for an example.

**Comment by vokhmak** [comment]
seems I finally fixed that: 
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/58312de0-5e75-432c-9ddf-212ec2e3fab7">

**Comment by vokhmak** [comment]
finally fixed that: 
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/58312de0-5e75-432c-9ddf-212ec2e3fab7">

previously I had a bunch of outdated commits and file changes mixed with my new code
