### ISSUE TITLE
Error while running "make init test-ui" command

### ISSUE THREAD

**Issue by slavas490** [ProxeusApp/proxeus-core#561]
There is an issue with build while it's running "make init test-ui" command, which came up in #452 

Please take a look at this pipeline: https://app.circleci.com/pipelines/github/ProxeusApp/proxeus-core/1798/workflows/c734238e-c81b-44b6-82df-7bba85035568/jobs/10989

<img width="764" alt="image" src="https://github.com/ProxeusApp/proxeus-core/assets/12787657/d3d10dbe-1f96-48d6-bb86-0d0b436717da">

**Comment by slavas490** [comment]
the only possible way is to use something like "wait until Proxeus has started"

**Comment by loleg** [comment]
Possibly related to #546 ?

**Comment by slavas490** [comment]
Not sure. If you open my most recent pull request (https://github.com/ProxeusApp/proxeus-core/pull/565) you'll see that the same test "ci/circleci: test-go — Your tests failed on CircleCI" was passed successfully

**Comment by loleg** [comment]
See [Makefile patch](https://github.com/ProxeusApp/proxeus-core/pull/565/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R68).
