### ISSUE TITLE
 Font centered 

### ISSUE THREAD

**Issue by wuk-j** [ProxeusApp/proxeus-core#676]
### Subject of the issue
The font inside the circle is not centered
![image](https://github.com/user-attachments/assets/a9d3be65-c6cb-4bbf-8789-b79e5c13837f)

### tips
Can it be exported as PNG？

**Comment by wuk-j** [comment]
![image](https://github.com/user-attachments/assets/a35ba8a7-906e-44ab-8fba-3bd8cb3d6b1c)

**Comment by loleg** [comment]
Wrong repository :) I think you were looking for https://github.com/visjs/vis-network
